//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnicomWeb.LocationService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Route", Namespace="http://schemas.datacontract.org/2004/07/TradeServices.Models")]
    [System.SerializableAttribute()]
    public partial class Route : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ParentIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isDeletedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isFolderField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ParentId {
            get {
                return this.ParentIdField;
            }
            set {
                if ((this.ParentIdField.Equals(value) != true)) {
                    this.ParentIdField = value;
                    this.RaisePropertyChanged("ParentId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isDeleted {
            get {
                return this.isDeletedField;
            }
            set {
                if ((this.isDeletedField.Equals(value) != true)) {
                    this.isDeletedField = value;
                    this.RaisePropertyChanged("isDeleted");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isFolder {
            get {
                return this.isFolderField;
            }
            set {
                if ((this.isFolderField.Equals(value) != true)) {
                    this.isFolderField = value;
                    this.RaisePropertyChanged("isFolder");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteTripEx", Namespace="http://schemas.datacontract.org/2004/07/TradeServices.Models")]
    [System.SerializableAttribute()]
    public partial class RouteTripEx : UnicomWeb.LocationService.RouteTrip {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstOutletAdrressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FirstOutletNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastOutletAdrressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastOutletNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RouteNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstOutletAdrress {
            get {
                return this.FirstOutletAdrressField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstOutletAdrressField, value) != true)) {
                    this.FirstOutletAdrressField = value;
                    this.RaisePropertyChanged("FirstOutletAdrress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstOutletName {
            get {
                return this.FirstOutletNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FirstOutletNameField, value) != true)) {
                    this.FirstOutletNameField = value;
                    this.RaisePropertyChanged("FirstOutletName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastOutletAdrress {
            get {
                return this.LastOutletAdrressField;
            }
            set {
                if ((object.ReferenceEquals(this.LastOutletAdrressField, value) != true)) {
                    this.LastOutletAdrressField = value;
                    this.RaisePropertyChanged("LastOutletAdrress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastOutletName {
            get {
                return this.LastOutletNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastOutletNameField, value) != true)) {
                    this.LastOutletNameField = value;
                    this.RaisePropertyChanged("LastOutletName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RouteName {
            get {
                return this.RouteNameField;
            }
            set {
                if ((object.ReferenceEquals(this.RouteNameField, value) != true)) {
                    this.RouteNameField = value;
                    this.RaisePropertyChanged("RouteName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RouteTrip", Namespace="http://schemas.datacontract.org/2004/07/TradeServices.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnicomWeb.LocationService.RouteTripEx))]
    public partial class RouteTrip : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DistanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<double> DistanceBetweenCheckInField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> FirstOutletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.Guid> LastOutletField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MaxCheckInTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> MinCheckInTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime RouteDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RouteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> Distance {
            get {
                return this.DistanceField;
            }
            set {
                if ((this.DistanceField.Equals(value) != true)) {
                    this.DistanceField = value;
                    this.RaisePropertyChanged("Distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<double> DistanceBetweenCheckIn {
            get {
                return this.DistanceBetweenCheckInField;
            }
            set {
                if ((this.DistanceBetweenCheckInField.Equals(value) != true)) {
                    this.DistanceBetweenCheckInField = value;
                    this.RaisePropertyChanged("DistanceBetweenCheckIn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> FirstOutlet {
            get {
                return this.FirstOutletField;
            }
            set {
                if ((this.FirstOutletField.Equals(value) != true)) {
                    this.FirstOutletField = value;
                    this.RaisePropertyChanged("FirstOutlet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> LastOutlet {
            get {
                return this.LastOutletField;
            }
            set {
                if ((this.LastOutletField.Equals(value) != true)) {
                    this.LastOutletField = value;
                    this.RaisePropertyChanged("LastOutlet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MaxCheckInTime {
            get {
                return this.MaxCheckInTimeField;
            }
            set {
                if ((this.MaxCheckInTimeField.Equals(value) != true)) {
                    this.MaxCheckInTimeField = value;
                    this.RaisePropertyChanged("MaxCheckInTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> MinCheckInTime {
            get {
                return this.MinCheckInTimeField;
            }
            set {
                if ((this.MinCheckInTimeField.Equals(value) != true)) {
                    this.MinCheckInTimeField = value;
                    this.RaisePropertyChanged("MinCheckInTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RouteDate {
            get {
                return this.RouteDateField;
            }
            set {
                if ((this.RouteDateField.Equals(value) != true)) {
                    this.RouteDateField = value;
                    this.RaisePropertyChanged("RouteDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RouteId {
            get {
                return this.RouteIdField;
            }
            set {
                if ((this.RouteIdField.Equals(value) != true)) {
                    this.RouteIdField = value;
                    this.RaisePropertyChanged("RouteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelOutletCheckInEx", Namespace="http://schemas.datacontract.org/2004/07/TradeServices.Models")]
    [System.SerializableAttribute()]
    public partial class ModelOutletCheckInEx : UnicomWeb.LocationService.ModelOutletCheckIn {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OutletField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Outlet {
            get {
                return this.OutletField;
            }
            set {
                if ((object.ReferenceEquals(this.OutletField, value) != true)) {
                    this.OutletField = value;
                    this.RaisePropertyChanged("Outlet");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelOutletCheckIn", Namespace="http://schemas.datacontract.org/2004/07/TradeServices.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnicomWeb.LocationService.ModelOutletCheckInEx))]
    public partial class ModelOutletCheckIn : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongtitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid OutletIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RouteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInTime {
            get {
                return this.CheckInTimeField;
            }
            set {
                if ((this.CheckInTimeField.Equals(value) != true)) {
                    this.CheckInTimeField = value;
                    this.RaisePropertyChanged("CheckInTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid OutletId {
            get {
                return this.OutletIdField;
            }
            set {
                if ((this.OutletIdField.Equals(value) != true)) {
                    this.OutletIdField = value;
                    this.RaisePropertyChanged("OutletId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RouteId {
            get {
                return this.RouteIdField;
            }
            set {
                if ((this.RouteIdField.Equals(value) != true)) {
                    this.RouteIdField = value;
                    this.RaisePropertyChanged("RouteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelRouteTripEx", Namespace="http://schemas.datacontract.org/2004/07/TradeServices.Models")]
    [System.SerializableAttribute()]
    public partial class ModelRouteTripEx : UnicomWeb.LocationService.ModelRouteTrip {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CheckInTimeStringField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int RowNumField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CheckInTimeString {
            get {
                return this.CheckInTimeStringField;
            }
            set {
                if ((object.ReferenceEquals(this.CheckInTimeStringField, value) != true)) {
                    this.CheckInTimeStringField = value;
                    this.RaisePropertyChanged("CheckInTimeString");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int RowNum {
            get {
                return this.RowNumField;
            }
            set {
                if ((this.RowNumField.Equals(value) != true)) {
                    this.RowNumField = value;
                    this.RaisePropertyChanged("RowNum");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ModelRouteTrip", Namespace="http://schemas.datacontract.org/2004/07/TradeServices.Models")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(UnicomWeb.LocationService.ModelRouteTripEx))]
    public partial class ModelRouteTrip : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime CheckInTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LatitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double LongtitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid RouteIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime CheckInTime {
            get {
                return this.CheckInTimeField;
            }
            set {
                if ((this.CheckInTimeField.Equals(value) != true)) {
                    this.CheckInTimeField = value;
                    this.RaisePropertyChanged("CheckInTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Latitude {
            get {
                return this.LatitudeField;
            }
            set {
                if ((this.LatitudeField.Equals(value) != true)) {
                    this.LatitudeField = value;
                    this.RaisePropertyChanged("Latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double Longtitude {
            get {
                return this.LongtitudeField;
            }
            set {
                if ((this.LongtitudeField.Equals(value) != true)) {
                    this.LongtitudeField = value;
                    this.RaisePropertyChanged("Longtitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid RouteId {
            get {
                return this.RouteIdField;
            }
            set {
                if ((this.RouteIdField.Equals(value) != true)) {
                    this.RouteIdField = value;
                    this.RaisePropertyChanged("RouteId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LocationService.ILocation")]
    public interface ILocation {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetTestString", ReplyAction="http://tempuri.org/ILocation/GetTestStringResponse")]
        string GetTestString();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetTestString", ReplyAction="http://tempuri.org/ILocation/GetTestStringResponse")]
        System.Threading.Tasks.Task<string> GetTestStringAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetAllActiveRoutes", ReplyAction="http://tempuri.org/ILocation/GetAllActiveRoutesResponse")]
        UnicomWeb.LocationService.Route[] GetAllActiveRoutes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetAllActiveRoutes", ReplyAction="http://tempuri.org/ILocation/GetAllActiveRoutesResponse")]
        System.Threading.Tasks.Task<UnicomWeb.LocationService.Route[]> GetAllActiveRoutesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetRouteTrip", ReplyAction="http://tempuri.org/ILocation/GetRouteTripResponse")]
        UnicomWeb.LocationService.RouteTripEx[] GetRouteTrip(string routeTripDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetRouteTrip", ReplyAction="http://tempuri.org/ILocation/GetRouteTripResponse")]
        System.Threading.Tasks.Task<UnicomWeb.LocationService.RouteTripEx[]> GetRouteTripAsync(string routeTripDate);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetCheckIn", ReplyAction="http://tempuri.org/ILocation/GetCheckInResponse")]
        UnicomWeb.LocationService.ModelOutletCheckInEx[] GetCheckIn(string routeTripDate, string routeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetCheckIn", ReplyAction="http://tempuri.org/ILocation/GetCheckInResponse")]
        System.Threading.Tasks.Task<UnicomWeb.LocationService.ModelOutletCheckInEx[]> GetCheckInAsync(string routeTripDate, string routeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetLocationTraking", ReplyAction="http://tempuri.org/ILocation/GetLocationTrakingResponse")]
        UnicomWeb.LocationService.ModelRouteTripEx[] GetLocationTraking(string routeTripDate, string routeId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ILocation/GetLocationTraking", ReplyAction="http://tempuri.org/ILocation/GetLocationTrakingResponse")]
        System.Threading.Tasks.Task<UnicomWeb.LocationService.ModelRouteTripEx[]> GetLocationTrakingAsync(string routeTripDate, string routeId);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ILocationChannel : UnicomWeb.LocationService.ILocation, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LocationClient : System.ServiceModel.ClientBase<UnicomWeb.LocationService.ILocation>, UnicomWeb.LocationService.ILocation {
        
        public LocationClient() {
        }
        
        public LocationClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LocationClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LocationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetTestString() {
            return base.Channel.GetTestString();
        }
        
        public System.Threading.Tasks.Task<string> GetTestStringAsync() {
            return base.Channel.GetTestStringAsync();
        }
        
        public UnicomWeb.LocationService.Route[] GetAllActiveRoutes() {
            return base.Channel.GetAllActiveRoutes();
        }
        
        public System.Threading.Tasks.Task<UnicomWeb.LocationService.Route[]> GetAllActiveRoutesAsync() {
            return base.Channel.GetAllActiveRoutesAsync();
        }
        
        public UnicomWeb.LocationService.RouteTripEx[] GetRouteTrip(string routeTripDate) {
            return base.Channel.GetRouteTrip(routeTripDate);
        }
        
        public System.Threading.Tasks.Task<UnicomWeb.LocationService.RouteTripEx[]> GetRouteTripAsync(string routeTripDate) {
            return base.Channel.GetRouteTripAsync(routeTripDate);
        }
        
        public UnicomWeb.LocationService.ModelOutletCheckInEx[] GetCheckIn(string routeTripDate, string routeId) {
            return base.Channel.GetCheckIn(routeTripDate, routeId);
        }
        
        public System.Threading.Tasks.Task<UnicomWeb.LocationService.ModelOutletCheckInEx[]> GetCheckInAsync(string routeTripDate, string routeId) {
            return base.Channel.GetCheckInAsync(routeTripDate, routeId);
        }
        
        public UnicomWeb.LocationService.ModelRouteTripEx[] GetLocationTraking(string routeTripDate, string routeId) {
            return base.Channel.GetLocationTraking(routeTripDate, routeId);
        }
        
        public System.Threading.Tasks.Task<UnicomWeb.LocationService.ModelRouteTripEx[]> GetLocationTrakingAsync(string routeTripDate, string routeId) {
            return base.Channel.GetLocationTrakingAsync(routeTripDate, routeId);
        }
    }
}
